Draft: Back for grouped
pyg-team/pyg-lib pull request #64
Opened 2022-07-13 21:42 UTC by puririshi98

2022-07-15 18:29 UTC, rusty1s requested changes

2022-07-15 18:29 UTC, rusty1s commented on pyg_lib/csrc/ops/matmul.cpp
> +      other_grad = reflatten(_grouped_matmul(grad_out_list, other_list));
Just use `at::stack(dim=0)` for this.

2022-07-15 18:29 UTC, rusty1s commented on pyg_lib/csrc/ops/matmul.cpp
> +      variable_list other_list = break_w_ptr(other, ptr);
`other` can be just split in the first dimension. It is a 3d-tensor.

2022-07-15 18:29 UTC, rusty1s commented on pyg_lib/csrc/ops/matmul.cpp
> +      variable_list grad_out_list = break_w_ptr(grad_out, ptr);
We can use `split` for this - similar to https://github.com/pyg-team/pyg-lib/blob/master/pyg_lib/csrc/ops/cuda/matmul_kernel.cu#L132-L136.

2022-07-15 18:29 UTC, rusty1s commented on pyg_lib/csrc/ops/matmul.cpp
> +    return_list.push_back(tens.slice(0, ptr.index({i - 1}).item<int>(),
This will break since `ptr` is a CUDA tensor.

2022-07-15 18:29 UTC, rusty1s commented on pyg_lib/csrc/ops/matmul.cpp
> +    auto input = get_input(input_and_other, input_len);
Let's just do this inline? I don't think we need to specify `get_input` and `get_other` here.

2022-07-15 18:29 UTC, rusty1s commented on pyg_lib/csrc/ops/matmul.cpp
> +      other_grad = reflatten(_grouped_matmul(grad_out_list, other_list));
This will still fail since it will not pick up the right dispatcher here, correct?

2022-07-25 21:58 UTC, puririshi98 commented
tested that forward and backward work for both segment and grouped matmul in pytorch

2022-07-26 08:25 UTC, rusty1s approved these changes
LGTM :)

2022-07-26 08:25 UTC, rusty1s commented on pyg_lib/csrc/ops/matmul.cpp
> +      other[i] = other[i].transpose(-2, -1).contiguous();
```suggestion
      other[i] = other[i].transpose(-2, -1);
```

2022-07-26 08:25 UTC, rusty1s commented on pyg_lib/csrc/ops/matmul.cpp
> +    if (torch::autograd::any_variable_requires_grad(input)) {
Do the same for other?

2022-07-27 00:52 UTC, puririshi98 commented
```
>>> import torch
>>> import pyg_lib
>>> inputs = torch.randn(8, 16).cuda()
>>> ptr = torch.tensor([0, 5, 8]).cuda()
>>> other = torch.randn((2, 16, 32), requires_grad=True, device='cuda:0')
>>> out = pyg_lib.ops.segment_matmul(inputs, ptr, other)
>>> out.sum().backward()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 399, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema pyg::grouped_matmul_kern.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function. 
```

the dispatching is working properly for segment_matmul now but the grouped_matmul kernel is not dispatching properly. i confirmed with debug prints that the inputs to grouped_matmul_kernel are in fact not empty, so the error message is misleading.

2022-07-27 22:37 UTC, puririshi98 commented
i found the issue [here](https://gitlab-master.nvidia.com/dl/pytorch/pytorch/-/blob/22.08_jetson/aten/src/ATen/core/op_registration/README.md#L256): 

> * The operator must return a single `Tensor` or multiple tensors as in `(Tensor, Tensor, Tensor)`. It cannot return a list `Tensor[]`, optional `Tensor?` or any primitive types.

2022-07-28 22:31 UTC, puririshi98 commented
ready to go, even added a little test https://github.com/puririshi98/pyg-lib/blob/back_for_grouped/test/ops/test_cutlass_autograd_ops.py

2022-08-01 14:41 UTC, merged

2022-08-01 14:42 UTC, rusty1s commented
I have merged this now. We can continue working on it in later PRs.